### ISSUE TITLE
Resistance of AUCTeX

### ISSUE THREAD

**Issue by whxvd** [NicolasPetton/emacs.d#2]
I just tried to assimilate auctex with borg, but had no success until now. auctex seems to very strongly want to be installed somewhere using `make install`. Until now I did not find any information about how to use auctex directly from the source directory. Google "auctex borg" yielded only this repo / your collective.

I tried to clone your collective in order to see how you did it. It seems that you modified auctex, so that your collective points to an auctex commit not present in e.g. emacsmirror/auctex. This means (a) I cannot see how you did it, and (b) `make bootstrap-borg bootstrap` bails out at auctex.

**Comment by whxvd** [comment]
If I do not get a reply to this issue until the end of this week, I most probably will start to search/ask auctex(-devel)@gnu.org about this. In any case, when figured out, I almost certainly will create a PR for a drone/auctex in emacscollective/emacs.g.

**Comment by NicolasPetton** [comment]
Sebastian Miele <notifications@github.com> writes:

> I tried to clone your collective in order to see how you did it. It
> seems that you modified auctex, so that your collective points to an
> auctex commit not present in e.g. emacsmirror/auctex. This means (a) I
> cannot see how you did it, and (b) `make bootstrap-borg bootstrap`
> bails out at auctex.

I have not modified auctex, I'm using the epkg repo url, which is
git@github.com:emacsmirror/auctex.git.

**Comment by whxvd** [comment]
Let em stand for `git@github.com:emacsmirror/auctex.git` and gnu stand for `https://git.savannah.gnu.org/git/auctex.git`.

em contains just a master branch that points to the same commit as does gnu's master branch. gnu additionally contains two branches. The objects of em should be a subset of the objects of gnu.

> I have not modified auctex, I'm using the epkg repo url, which is git@github.com:emacsmirror/auctex.git.

I tried again in a very fresh environment, but `make bootstrap-borg` followed by `make bootstrap` still yields:

```
--- [auctex] ---

Cloning into '/home/w/.emacs.d/lib/auctex'...
remote: Counting objects: 29607, done.
remote: Compressing objects: 100% (8485/8485), done.
remote: Total 29607 (delta 21097), reused 29607 (delta 21097), pack-reused 0
Receiving objects: 100% (29607/29607), 10.62 MiB | 134.00 KiB/s, done.
Resolving deltas: 100% (21097/21097), done.
fatal: Could not parse object '3ac4a91ae84a36643a9f5ed93e31f57bbd69e40b'.
futile: Checkout of '3ac4a91ae84a36643a9f5ed93e31f57bbd69e40b' into submodule path 'lib/auctex' failed
HEAD is now at b292942e Remove some obsolete functions
make: *** [lib/borg/borg.mk:69: bootstrap] Error 1
```

As far as I understand and checked it, `3ac4a91ae8...` is the commit that is stored for `master:lib/auctex` in `NicolasPetton/emacs.d`. (Try running `git submodule status | grep auctex`.)

`3ac4a91ae8...` definitely is not an sha of any object in em or gnu.

For the time being I do not use epkg. Just emacs.g - (epkg + dependencies). In order to be on the safe side, I bootstrapped a fresh `emacscollective/emacs.g` including `epkg` and assimilated `auctex` the epkg-way.

As expected, that does not yield `3ac4a91ae8...`, but the (sha of the) master branch (with its known complications, i.e. seeming to want to be `make install`ed somewhere before working). (And it does not yield em but gnu, although this is irrelevant.)

Aside: Neither `auctex` nor `(local/)auctex(-evince-sync.el)` is mentioned in your `init.el`. Maybe you did not use it for a very long time and things rebased / changed?

**Comment by TheBB** [comment]
Hi guys,

Found this issue because I was trying to solve this exact problem. This is how I did it.

Your `.gitmodules` entry should look like this.

```
[submodule "auctex"]
	path = lib/auctex
	url = https://git.savannah.gnu.org/git/auctex.git
	build-step = ./autogen.sh
	build-step = configure
	build-step = make
	build-step = "(borg-update-autoloads \"auctex\")"
```

AUCTeX's own build system creates a file called `auto-loads.el`, but borg adds its own magic to the autoloads file (in particular, there is code in there to push to `load-path`, so that borg does not do it explicitly by itself during init). For this reason I use borg's own mechanisms. Seems to work fine though.

Additionally you must load the file `tex-site.el` during init. When you install AUCTeX from elpa, the `auctex-autoloads.el` file contains a call to `(require 'tex-site)`. The one borg generates is missing this. That's probably not borg's fault. Indeed, if you grab AUCTeX from ELPA, you will find in `tex-site.el` the following

```elisp
;;; Ensure that loading the autoloads file also loads this file.
;;;###autoload (require 'tex-site)
```

This is missing from the version on savannah. I'm not sure *why* exactly. It's possible that I'm looking at a deliberate change between two versions of AUCTeX, but at any rate, so long as I `(require 'tex-site)` at startup, AUCTeX seems to work fine. To verify `(featurep 'latex)` should evaluate to true after opening a latex-file.

CC @tarsius because maybe he can shed some light on this. If not, no problem.

**Comment by georgek** [comment]
For anyone finding this, the above addition to `.gitmodules` should actually look like this:
```
[submodule "auctex"]
	path = lib/auctex
	url = https://git.savannah.gnu.org/git/auctex.git
	build-step = ./autogen.sh
	build-step = ./configure
	build-step = make
	build-step = "(borg-update-autoloads \"auctex\")"
```
After making the change build auctex by running `M-x borg-build auctex` then in case you use `use-package`, look at jwiegley's comment here: https://github.com/jwiegley/use-package/issues/379#issuecomment-258217014
